### ISSUE TITLE
installer fails when main.js is not the entry point

### ISSUE THREAD

**Issue by nerdoc** [nerdocs/vue-extensions#9]
per default, vue uses `src/main.js` as entry point. Some packages don't follow that example - if you e.g. use index.js, *vue-extensions* doesn't find your file and can't modify it, and so the installer crashes.
```
Error: ENOENT: no such file or directory, open 'src/main.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at /home/christian/tmp/django-vue-parcel/ui/node_modules/vue-cli-plugin-extensions/generator/index.js:29:28
    at runGenerator (/home/christian/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async invoke (/home/christian/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)
```

**Comment by nerdoc** [comment]
This is a bug of [vue-cli-plugin-extensions](https://github.com/nerdocs/vue-cli-plugin-extensions)!
